import { z } from 'zod'

export const siteSchema = z.object({
  site: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    lang: z.string().trim().min(1),
  }),
  header: z.object({
    casesLabel: z.string().trim().min(1),
  }),
  posts: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
    author: z.string().trim().min(1),
    readMoreText: z.string().trim().min(1),
    prevPageText: z.string().trim().min(1),
    nextPageText: z.string().trim().min(1),
    tocText: z.string().trim().min(1),
    backToPostsText: z.string().trim().min(1),
    nextPostText: z.string().trim().min(1),
    prevPostText: z.string().trim().min(1),
    recommendText: z.string().trim().min(1),
  }),
  tags: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  projects: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  cases: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  home: z.object({
    title: z.string().trim().min(1),
    subtitle: z.string().trim().min(1),
    intro: z.string().trim().min(1),
    socialLabel: z.string().trim().min(1),
    contributionsTitle: z.string().trim().min(1),
    contributionsDescription: z.string().trim().min(1),
    skillsTitle: z.string().trim().min(1),
    skillsDescription: z.string().trim().min(1),
    postsTitle: z.string().trim().min(1),
    pinnedLabel: z.string().trim().min(1),
    recentLabel: z.string().trim().min(1),
    postsSummarySuffix: z.string().trim().min(1),
  }),
  comments: z.object({
    language: z.string().trim().min(1),
  }),
  ui: z.object({
    rssFeedLabel: z.string().trim().min(1),
    languageSwitcherLabel: z.string().trim().min(1),
    languageOptionEnglish: z.string().trim().min(1),
    languageOptionPortuguese: z.string().trim().min(1),
    githubSourceLabel: z.string().trim().min(1),
    searchLabel: z.string().trim().min(1),
    searchTitle: z.string().trim().min(1),
    searchPlaceholder: z.string().trim().min(1),
    searchExact: z.string().trim().min(1),
    searchTypePrompt: z.string().trim().min(1),
    searchNoResults: z.string().trim().min(1),
    searchNoResultsDev: z.string().trim().min(1),
    commentsTitle: z.string().trim().min(1),
    tagSingular: z.string().trim().min(1),
    tagPlural: z.string().trim().min(1),
    postSingular: z.string().trim().min(1),
    postPlural: z.string().trim().min(1),
    totalSuffix: z.string().trim().min(1),
    tagsEmpty: z.string().trim().min(1),
    tagBackLabel: z.string().trim().min(1),
    projectsStars: z.string().trim().min(1),
    projectsForks: z.string().trim().min(1),
    projectsWebsite: z.string().trim().min(1),
    projectsGithub: z.string().trim().min(1),
    casesEmpty: z.string().trim().min(1),
    backToTop: z.string().trim().min(1),
    recommendedPostTitle: z.string().trim().min(1),
    viewPostsTaggedWithPrefix: z.string().trim().min(1),
    socialAriaLabelPrefix: z.string().trim().min(1),
  }),
})

export type SiteData = z.infer<typeof siteSchema>
