import { z } from 'zod'

export const siteSchema = z.object({
  site: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    lang: z.string().trim().min(1),
  }),
  header: z.object({
    casesLabel: z.string().trim().min(1),
  }),
  posts: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
    author: z.string().trim().min(1),
    readMoreText: z.string().trim().min(1),
    prevPageText: z.string().trim().min(1),
    nextPageText: z.string().trim().min(1),
    tocText: z.string().trim().min(1),
    backToPostsText: z.string().trim().min(1),
    nextPostText: z.string().trim().min(1),
    prevPostText: z.string().trim().min(1),
    recommendText: z.string().trim().min(1),
  }),
  tags: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  projects: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  cases: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
  }),
  newSite: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
    sessionInvalidPrefixLabel: z.string().trim().min(1),
    sessionInvalidLinkLabel: z.string().trim().min(1),
    existingSiteLabel: z.string().trim().min(1),
    existingSiteLinkLabel: z.string().trim().min(1),
    checkoutSelfLinkLabel: z.string().trim().min(1),
    checkoutCustomerLinkLabel: z.string().trim().min(1),
    checkoutCustomerCopyLabel: z.string().trim().min(1),
    checkoutCustomerCopiedLabel: z.string().trim().min(1),
    checkoutTrackPaymentLabel: z.string().trim().min(1),
  }),
  mySite: z.object({
    title: z.string().trim().min(1),
    description: z.string().trim().min(1),
    introduce: z.string().trim().min(1),
    sessionInvalidPrefixLabel: z.string().trim().min(1),
    sessionInvalidLinkLabel: z.string().trim().min(1),
    appCardLabel: z.string().trim().min(1),
    appCardLinkLabel: z.string().trim().min(1),
  }),
  home: z.object({
    title: z.string().trim().min(1),
    subtitle: z.string().trim().min(1),
    intro: z.string().trim().min(1),
    socialLabel: z.string().trim().min(1),
    gmnReportLabel: z.string().trim().min(1),
    workTitle: z.string().trim().min(1),
    workDescription: z.string().trim().min(1),
    workCardDiscountTitle: z.string().trim().min(1),
    workCardPaymentLinkTitle: z.string().trim().min(1),
    workCardDiscountItems: z.array(z.string().trim().min(1)).min(1),
    workCardPaymentLinkItems: z.array(z.string().trim().min(1)).min(1),
    workCardDiscountYouPayLabel: z.string().trim().min(1),
    workCardDiscountYouPayValue: z.string().trim().min(1),
    workCardDiscountYouProfitLabel: z.string().trim().min(1),
    workCardDiscountYouProfitValue: z.string().trim().min(1),
    workCardPaymentYouPayLabel: z.string().trim().min(1),
    workCardPaymentYouPayValue: z.string().trim().min(1),
    workCardPaymentYouProfitLabel: z.string().trim().min(1),
    workCardPaymentYouProfitValue: z.string().trim().min(1),
    workInfoDeferredPayout: z.string().trim().min(1),
    sitesTitle: z.string().trim().min(1),
    sitesDescription: z.string().trim().min(1),
    skillsTitle: z.string().trim().min(1),
    skillsDescription: z.string().trim().min(1),
    skillsSubheading: z.string().trim().min(1),
    pageSpeedScores: z.object({
      performance: z.string().trim().min(1),
      accessibility: z.string().trim().min(1),
      bestPractices: z.string().trim().min(1),
      seo: z.string().trim().min(1),
    }),
    postsTitle: z.string().trim().min(1),
    pinnedLabel: z.string().trim().min(1),
    recentLabel: z.string().trim().min(1),
    postsSummarySuffix: z.string().trim().min(1),
  }),
  comments: z.object({
    language: z.string().trim().min(1),
  }),
  ui: z.object({
    rssFeedLabel: z.string().trim().min(1),
    languageSwitcherLabel: z.string().trim().min(1),
    languageOptionEnglish: z.string().trim().min(1),
    languageOptionPortuguese: z.string().trim().min(1),
    githubSourceLabel: z.string().trim().min(1),
    searchLabel: z.string().trim().min(1),
    searchTitle: z.string().trim().min(1),
    searchPlaceholder: z.string().trim().min(1),
    searchExact: z.string().trim().min(1),
    searchTypePrompt: z.string().trim().min(1),
    searchNoResults: z.string().trim().min(1),
    searchNoResultsDev: z.string().trim().min(1),
    commentsTitle: z.string().trim().min(1),
    tagSingular: z.string().trim().min(1),
    tagPlural: z.string().trim().min(1),
    postSingular: z.string().trim().min(1),
    postPlural: z.string().trim().min(1),
    totalSuffix: z.string().trim().min(1),
    tagsEmpty: z.string().trim().min(1),
    tagBackLabel: z.string().trim().min(1),
    projectsStars: z.string().trim().min(1),
    projectsForks: z.string().trim().min(1),
    projectsWebsite: z.string().trim().min(1),
    projectsGithub: z.string().trim().min(1),
    casesEmpty: z.string().trim().min(1),
    backToTop: z.string().trim().min(1),
    recommendedPostTitle: z.string().trim().min(1),
    viewPostsTaggedWithPrefix: z.string().trim().min(1),
    socialAriaLabelPrefix: z.string().trim().min(1),
    heatmapDateLocale: z.string().trim().min(1),
    heatmapDateFormat: z.enum(['long', 'numeric', 'dot', 'long-pt']),
    heatmapRestDay: z.string().trim().min(1),
    heatmapSiteSingular: z.string().trim().min(1),
    heatmapSitePlural: z.string().trim().min(1),
  }),
})

export type SiteData = z.infer<typeof siteSchema>
